// folon-marketplace/src/components/ui/Input.tsx
import { cn } from '@/lib/utils'
import { InputHTMLAttributes, forwardRef } from 'react'

interface InputProps extends InputHTMLAttributes<HTMLInputElement> {
  label?: string
  error?: string
}

const Input = forwardRef<HTMLInputElement, InputProps>(
  ({ className, label, error, id, ...props }, ref) => {
    return (
      <div className="flex flex-col gap-1.5">
        {label && (
          <label htmlFor={id} className="text-sm font-medium text-gray-700">
            {label}
          </label>
        )}
        <input
          ref={ref}
          id={id}
          className={cn(
            'w-full rounded-xl border border-gray-200 px-4 py-3 text-sm bg-white text-[#1a1a1a] placeholder:text-gray-400 transition-all outline-none focus:border-[#4CA771] focus:ring-2 focus:ring-[#4CA771]/20',
            error && 'border-red-400 focus:border-red-400 focus:ring-red-200',
            className
          )}
          {...props}
        />
        {error && <p className="text-xs text-red-500">{error}</p>}
      </div>
    )
  }
)
Input.displayName = 'Input'
export default Input

// frontend/app/components/ui/Input.vue
<script setup lang="ts">
defineProps<{
  label?: string
  error?: string
  type?: string
  placeholder?: string
  required?: boolean
  autocomplete?: string
}>()

const modelValue = defineModel<string>()
</script>

<template>
  <div class="flex flex-col gap-1">
    <label v-if="label" class="text-sm font-medium text-gray-700">
      {{ label }}
      <span v-if="required" class="text-red-500 ml-0.5" aria-hidden="true">*</span>
    </label>
    <input
      v-model="modelValue"
      :type="type ?? 'text'"
      :placeholder="placeholder"
      :required="required"
      :autocomplete="autocomplete"
      :class="[
        'w-full px-3 py-2 rounded-lg border text-sm focus:outline-none focus:ring-2 focus:ring-brand-500 transition-colors',
        error ? 'border-red-400 focus:ring-red-400' : 'border-gray-300',
      ]"
    />
    <p v-if="error" class="text-xs text-red-600" role="alert">{{ error }}</p>
  </div>
</template>
