// folon-marketplace/src/components/ui/Spinner.tsx
import { cn } from '@/lib/utils'

export default function Spinner({ className }: { className?: string }) {
  return (
    <svg
      className={cn('animate-spin text-[#4CA771]', className)}
      viewBox="0 0 24 24"
      fill="none"
      aria-hidden="true"
    >
      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v8H4z" />
    </svg>
  )
}

// frontend/app/components/ui/Spinner.vue
<script setup lang="ts">
defineProps<{ size?: 'sm' | 'md' | 'lg' }>()
</script>

<template>
  <svg
    :class="[
      'animate-spin text-brand-600',
      { 'w-4 h-4': size === 'sm', 'w-6 h-6': (size ?? 'md') === 'md', 'w-8 h-8': size === 'lg' },
    ]"
    viewBox="0 0 24 24"
    fill="none"
    aria-label="Loading"
  >
    <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4" />
    <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
  </svg>
</template>
