// folon-marketplace/src/components/storefront/ProductCard.tsx
'use client'
import Link from 'next/link'
import Image from 'next/image'
import { useRouter } from 'next/navigation'
import { formatPrice } from '@/lib/utils'
import { addToCart } from '@/lib/cart/store'
import { useT } from '@/lib/i18n'
import { ShoppingCart, ShoppingBag, Check, Package } from 'lucide-react'
import { useState } from 'react'

interface Product {
  id: string
  name: string
  price: number
  compareAtPrice?: number | null
  bundle5Price?: number | null
  bundle10Price?: number | null
  images: string[]
  stock: number
  category?: { name: string; slug: string } | null
}

export default function ProductCard({ product }: { product: Product }) {
  const { t } = useT()
  const router = useRouter()
  const [added, setAdded] = useState(false)
  const inStock = product.stock > 0

  function handleAddToCart(e: React.MouseEvent) {
    e.preventDefault()
    e.stopPropagation()
    if (!inStock) return
    addToCart({ productId: product.id, name: product.name, price: product.price, originalPrice: product.price, bundle5Price: product.bundle5Price ?? undefined, bundle10Price: product.bundle10Price ?? undefined, image: product.images[0] ?? '' })
    setAdded(true)
    setTimeout(() => setAdded(false), 1500)
  }

  function handleBuyNow(e: React.MouseEvent) {
    e.preventDefault()
    e.stopPropagation()
    if (!inStock) return
    addToCart({ productId: product.id, name: product.name, price: product.price, originalPrice: product.price, bundle5Price: product.bundle5Price ?? undefined, bundle10Price: product.bundle10Price ?? undefined, image: product.images[0] ?? '' })
    router.push('/checkout')
  }

  return (
    <Link href={`/products/${product.id}`} className="group block">
      <div className="bg-white rounded-2xl overflow-hidden border border-gray-100 hover:border-[#4CA771]/30 hover:shadow-[0_8px_24px_rgba(76,167,113,0.12)] transition-all duration-300 h-full flex flex-col">

        {/* Image */}
        <div className="relative aspect-square bg-gray-50 overflow-hidden">
          {product.images[0] ? (
            <Image
              src={product.images[0]}
              alt={product.name}
              fill
              className="object-cover group-hover:scale-105 transition-transform duration-500"
              sizes="(max-width: 480px) 50vw, 200px"
            />
          ) : (
            <div className="w-full h-full flex flex-col items-center justify-center gap-2 bg-gray-50">
              <Package className="w-8 h-8 text-gray-200" />
            </div>
          )}

          {/* Category chip */}
          {product.category && (
            <span className="absolute top-2 left-2 bg-white/90 backdrop-blur-sm text-[10px] font-semibold text-[#4CA771] px-2 py-0.5 rounded-full">
              {product.category.name}
            </span>
          )}

          {/* Floating cart button */}
          {inStock && (
            <button
              onClick={handleAddToCart}
              aria-label={t.addToCart}
              className={`absolute top-2 right-2 w-8 h-8 rounded-full flex items-center justify-center shadow-md transition-all duration-200 ${
                added
                  ? 'bg-[#4CA771] text-white scale-110'
                  : 'bg-white text-gray-600 hover:bg-[#4CA771] hover:text-white hover:scale-110'
              }`}
            >
              {added
                ? <Check className="w-3.5 h-3.5" strokeWidth={2.5} />
                : <ShoppingCart className="w-3.5 h-3.5" />
              }
            </button>
          )}

          {/* Out of stock overlay */}
          {!inStock && (
            <div className="absolute inset-0 bg-white/60 backdrop-blur-[1px] flex items-center justify-center">
              <span className="text-[11px] font-semibold text-gray-500 bg-white px-3 py-1 rounded-full border border-gray-200 shadow-sm">
                {t.soldOut}
              </span>
            </div>
          )}
        </div>

        {/* Info */}
        <div className="p-3 flex flex-col flex-1 gap-2">
          <p className="text-[13px] font-medium text-gray-800 line-clamp-2 leading-snug flex-1">
            {product.name}
          </p>

          <div className="flex items-baseline gap-1.5">
            {product.compareAtPrice ? (
              <span className="text-xs text-gray-400 line-through">{formatPrice(product.compareAtPrice)}</span>
            ) : null}
            <span className="text-base font-bold text-[#4CA771] tracking-tight">{formatPrice(product.price)}</span>
          </div>

          {inStock ? (
            <button
              onClick={handleBuyNow}
              aria-label={t.buyNow}
              className="w-full flex items-center justify-center gap-1.5 py-2 rounded-xl bg-[#4CA771] text-white text-xs font-semibold hover:bg-[#3a8a5c] active:scale-95 transition-all duration-150"
            >
              <ShoppingBag className="w-3.5 h-3.5" />
              {t.buyNow}
            </button>
          ) : (
            <div className="py-2 text-center text-[11px] font-medium text-gray-400 bg-gray-50 rounded-xl">
              {t.soldOut}
            </div>
          )}
        </div>
      </div>
    </Link>
  )
}

// frontend/app/components/product/ProductCard.vue
<script setup lang="ts">
import type { Product } from '~/types'
import { formatPrice } from '~/utils/format'
import { useCart } from '~/composables/useCart'

const props = defineProps<{ product: Product }>()
const { addItem } = useCart()
const added = ref(false)

function handleAddToCart() {
  addItem({
    productId: props.product.id,
    name: props.product.name,
    price: props.product.price,
    image: props.product.images[0] ?? '',
    quantity: 1,
    slug: props.product.slug,
  })
  added.value = true
  setTimeout(() => { added.value = false }, 1500)
}

const isOutOfStock = computed(() => props.product.stock === 0)
</script>

<template>
  <article class="group flex flex-col bg-white rounded-xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow overflow-hidden">
    <NuxtLink :to="`/products/${product.slug}`" class="block relative aspect-square overflow-hidden bg-gray-50">
      <img
        v-if="product.images[0]"
        :src="product.images[0]"
        :alt="product.name"
        class="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
        loading="lazy"
      />
      <div v-else class="w-full h-full flex items-center justify-center text-gray-300">
        <svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      </div>
      <div v-if="isOutOfStock" class="absolute inset-0 bg-white/70 flex items-center justify-center">
        <UiBadge variant="neutral">Sold Out</UiBadge>
      </div>
    </NuxtLink>

    <div class="p-4 flex flex-col flex-1">
      <NuxtLink :to="`/products/${product.slug}`">
        <h2 class="font-semibold text-gray-900 hover:text-brand-600 transition-colors text-sm leading-snug mb-1">
          {{ product.name }}
        </h2>
      </NuxtLink>
      <p class="text-brand-600 font-bold text-base mt-auto pt-2">{{ formatPrice(product.price) }}</p>

      <button
        v-if="!isOutOfStock"
        :class="[
          'mt-3 w-full py-2 rounded-lg text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-brand-500',
          added
            ? 'bg-green-600 text-white'
            : 'bg-brand-600 hover:bg-brand-700 text-white',
        ]"
        @click.prevent="handleAddToCart"
      >
        {{ added ? 'Added!' : 'Add to Cart' }}
      </button>
      <button
        v-else
        class="mt-3 w-full py-2 rounded-lg text-sm font-medium border border-gray-300 text-gray-500 cursor-not-allowed"
        disabled
        aria-disabled="true"
      >
        Notify Me
      </button>
    </div>
  </article>
</template>
